### ISSUE TITLE
Node goes to 100% CPU exact 24 hours before switching to summertime

### ISSUE THREAD

**Issue by BramBoos** [node-schedule/node-schedule#132]
Last night at exactly 3AM my backup server was calling for help, the CPU went to 100% and nothing worked anymore. At 3AM normally starts the backup but not last night. It never came to the console.log on the first line of the backup function (it crashed before the backup actually happen).

The thing is, I live in the Netherlands, tonight the time goes at 3AM to 4AM (summertime). Can this have influence on the node-schedule module? And how can I debug this? The tests are running okay, but when I put node schedule back in my code it crashes immediately. Is there a option to see what is causing this. I have reinstalled and rebooted the server and all node plugins but nothing works.

Thanks!

**Comment by oliversalzburg** [comment]
I also reported this earlier in #131 but that was due to an outdated version.

However, exactly when the DST switch happens, another bug is in effect and will cause job invocations to stay indefinitely.

![](http://i.imgur.com/6LVIdy9.png)

**Comment by jonhester** [comment]
Interesting. I have some plans to address jobs that are unable to run for the next release so I'll make sure to account for this when I get to that point.

@BramBoos How are you scheduling the job(s)? Could you provide some example code?

**Comment by oliversalzburg** [comment]
It's not that jobs are not able to run. The issue *we* were initially having was related to the `while(true){ /* add 1 hour until a break condition is met */ }`, which never reaches the break condition. I'm not too sure if this was really fixed or if it simply was no longer a problem after the server reboot.

I didn't get too deep into debugging at 2/3 AM, but either jobs were being rescheduled for the next tick indefinitely or they were never recognized as finished. I assume the former.

**Comment by santigimeno** [comment]
@BramBoos You had the job scheduled exactly at 3 AM, right? The problem is probably that due to the date switch, the 3-4 AM date range does not exist. Of course, this should not make node-schedule go 100%. I'll look into it

**Comment by santigimeno** [comment]
@BramBoos One more question: what type of scheduling are you using? cron, date, recurrence rule?

**Comment by santigimeno** [comment]
After looking a bit into it I've found a couple of issues when scheduling a job in an non existent date due to date switch.

Taking into account that in my timezone, the date-switch happened from 2to3AM:

- When using `date` scheduling the job would be scheduled one hour before. 
```
> new Date(2015, 02, 29, 1, 10, 0).getTime() === new Date(2015, 02, 29, 2, 10, 0).getTime()
true
``` 
- When using `recurrence` scheduling the date calculated is also wrong
```
// In this case the job would be executed the following day: Mon Mar 30 2015 02:00:00 GMT+0200
var job = schedule.scheduleJob({
    year : 2015,
    month : 2,
    day : 29,
    hour: 2,
    minute : 0,
    second : 0
}, function() {
});
```
These problems should be solved if we relied in UTC instead of the system date. See https://github.com/node-schedule/node-schedule/issues/34 and https://github.com/node-schedule/node-schedule/issues/70

I haven't been able to reproduce the 100%CPU issue though. If you could provide a simple test case I could look into it. You can use `datefudge` to fake the date in your system.

**Comment by BramBoos** [comment]
I used this code:

```
        var rule = new schedule.RecurrenceRule();
        rule.hour = 3;
        rule.minute = 0;

        schedule.scheduleJob(rule, scheduleServer.backup);
```

The day after everything went well again. After that I switched to UTC timezone so it doesn't happen again. The only thing that is weird is that after a reboot node goes back to 100% CPU (I thought that the schedule was stored in RAM so a reboot would reset it).

If it wasn't happening after a 12 hour work day I would have checked where it came from but my bed was calling.

**Comment by santigimeno** [comment]
@BramBoos Thanks for the code snippet, can't reproduce it though :(. A couple of questions: 
- Is this 100%CPU issue still happening to you?
- What `node-schedule` version are you using?

**Comment by michAtEl** [comment]
We had the same 100% load-issue with this software:
node-schedule v0.1.16, using cron-parser 0.3.6
Ubuntu 12.04.5 LTS 
node  v0.10.36
pm2 0.12.7

This is a snippet from our app:
```javascript
var schedule = require('node-schedule');
var rule = new schedule.RecurrenceRule();
var recurrenceJob = schedule.scheduleJob( {hour: 3, minute: 0}, function() {
    // do something important
});
```
I think I was able to find the problem:
I start my app with datefudge "2015-03-29 1:04" node --debug-brk app.js
In the loop while(true) in RecurrenceRule.prototype.nextInvocationDate (shedule.js) the method next.addHour() is called. But this call doesn't change the Date next and the loop while(true) ist infinite!
This is because of the implementation of addHour(), that is used:
```javascript
Date.prototype.addHour = function() {
  this.setHours(this.getHours() + 1);
};
```
this.getHours() is 1. this.getHours() + 1 is 2. this.setHours(2) sets the hour to 1 because 2 doesn't exist (DST).

The implementation of addHour() that is used is _not_ the implementation in the file increment.js because cron-parser is adding a function addHour to Date.prototype. In my opinion, this is bad behaviour. I suppose that the implementation in increment.js should work.
With the implementation of addHour in the master-Branch of cron-parser, this bug should not occur.
Anyway, I suggest:
- cron-parser should not modify Objects like Date.prototype. Instead, cron-parser could export the function addHour (and similar functions like addYear ...) via module.exports.
- node-schedule should use its own implementations of addHour (...) or implementations, that are exported by cron-parser via module.exports.

I think, this would provide apis for cron-parser and node-schedule that are cleaner and more traceable.

**Comment by jonhester** [comment]
Good call. I am already looking at changing this for the next major version.

**Comment by santigimeno** [comment]
@michAtEl Thanks for the thorough analysis! I could finally reproduce the problem. The good news is that it doesn't happen in the latest version `0.2.6`.
@jonhester @tejasmanohar What do we do?
- Open an issue in `cron-parser` and propose the changes @michAtEl suggested?
- Just drop `increment.js` and `addDateConvenienceMethods` and trust in the `cron-parser` implementation of the helper functions?

**Comment by tejasmanohar** [comment]
@santigimeno I'd suggest option #2 until #1 is implemented (if it ever is).

**Comment by tejasmanohar** [comment]
This has been solved in https://github.com/node-schedule/node-schedule/tree/dev.
