### ISSUE TITLE
Add method of persistency

### ISSUE THREAD

**Issue by 240ch** [node-schedule/node-schedule#177]
Is there a way to sync multiple instances of a Node.js app and prevent them from executing a schedule-job more than once?

**Comment by santigimeno** [comment]
No, I don't think so

**Comment by IsaiahJTurner** [comment]
Could this be added as a feature? It's something I need as well. Alternatively, is there another module that provides this behavior?

**Comment by santigimeno** [comment]
I think it could be a good addition.  I don't know of an alternative module though.

**Comment by tejasmanohar** [comment]
In order to share a schedule b/w multiple instances, we'd need a method of persistence... you _could_ always do it by saving the Schedule object properties in some external data store like Redis but there's nothing out-of-the-box for this right now.

Would you guys expand on your use case a bit more? Do you need to share a schedule between multiple Node.js processes on one server? Completely separate instances? @IsaiahJTurner @240ch 

I think this is a good feature that I could work on developing but also want to keep the module pretty lean.

**Comment by 240ch** [comment]
I've got an application that queries a soap-webservice one a minute and saves its response in a mongodb. The application itself is also a REST-webservice and offers history of the queried data. To be scalable, I've deployed the app to a Cloud Foundry (application cloud) provider. There are several instances running simultaneously and unfortunately every instance is querying the soap-webservice on its own once a minute resulting in multiple data for this exact minute. I went ahead and tried synchronise the instance with a shared mongodb but I haven't figured out how to lock reads/writes to mongodb, so there were still multiple entries for one minute. I also tried an in-memory-grid (Hazelcast) with an eventbus  (Vert.x) but had to realise that my instances won't find eachother due to technical limitations of my Cloud Foundry provider (Hazelcast needs Multicast enabled, which isn't). So my current - and work-in-progress - try is to synchronise the instances through rabbitMQ, a message broker for Cloud Foundry but it isn't working that smooth yet :)

You see, I tried quite some approaches. The very easiest way would be a scheduler that synchronises itself among instances. Bear in mind that you cannot expect the user to know the IP addresses of other instances. I think support for rabbitMQ and/or mongodb would be the best you could offer here. 

Thank you very much for your efforts and best regards

**Comment by IsaiahJTurner** [comment]
# Problem
My application uses Heroku with multiple Dynos (servers). It is a live video service where users can schedule when they will go live. I use MongoDB to store the current state (SCHEDULED, LIVE, OVER, or MISSED) but then send it to Firebase to keep this state in sync with the clients.

The problem is with sending the state to Firebase. I want it to automatically send the state as MISSED after the scheduled live time (using node-schedule "Date based Scheduling") if the presenter did not go live. The problem is, I don't know if my server will restart (or an instance be destroyed completely) between scheduling the live stream (when I would ideal schedule the node-schedule job as well) and the scheduled date.

My current solution is hacky. I schedule a cron job for every minute on the server start (every instance, very redundant) that keeps checking for any new scheduled live streams. Then, if a new stream is detected (or an old scheduled stream that has not gone live yet is found) if creates a Date based job. This job is also redundant as each and every server schedules it.

**Comment by scaryguy** [comment]
+1 for the feature proposal. But  I have a simpler question: How do you share state inside a single instance while Job is created in a separate `.js` file and if you wan't to access it from another `.js` file?

Let's say I have a job created inside `lib/one.js` file:

```js
var cue_out_scheduler = scheduler(date, function cue_out_scheduler() { .... }
```

And I want to cancel this specific `cue_out_scheduler` file inside `lib/two.js` file.

```js
cue_out_scheduler.cancel();
```

How to do that?

**Comment by tejasmanohar** [comment]
@scaryguy

you can do this with [modules](https://nodejs.org/api/modules.html). please open another issue, tag me, and i'll include a detailed response there :smile:

**Comment by scaryguy** [comment]
I did it @tejasmanohar :) Thanks in advence

**Comment by jtmarmon** [comment]
we used [taskrabbit/node-resqueue](https://github.com/taskrabbit/node-resque) for this. worked great

**Comment by jagged3dge** [comment]
Could provide a plugin architecture for persistence that allows the module's consumers to define their own storage/persistence mechanism. Pretty much like how [multer](https://github.com/expressjs/multer) does for disk storage. It provides a basic in-memory storage by default, but allows for module consumers to replace it with their own storage mechanism.

Just need to provide proper documentation on what methods the storage plugin should have, and I'm sure we can take it from there. We would then be able to use any data-storage we like. Be it Redis, Mongo, MySQL, or even a cron-ish text file.

**Comment by tejasmanohar** [comment]
Yes, when/if this is completed, it should follow an adapter model.

**Comment by jagged3dge** [comment]
I think I saw some other scheduling module on npm that uses this kind of persistence architecture. I'll dig around npm a little and get back to you. Maybe we can get some definite pointers to get this adapter model started.

**Comment by jagged3dge** [comment]
Found it. [delayed-events](https://www.npmjs.com/package/delayed-events)

I did try this module some time ago, but I couldn't get myself to like the API except for the persistence feature.

**Comment by tejasmanohar** [comment]
+1 for using [taskrabbit/node-resqueue](https://github.com/taskrabbit/node-resque) with this module. we're moving our stuff at [AutoLotto](https://github.com/autolotto) over to this as well.

**Comment by tejasmanohar** [comment]
i'd rather leave things like node-resque to manage this and keep node-schedule lean.
