### ISSUE TITLE
Monthly job firing daily

### ISSUE THREAD

**Issue by hashbangdev1** [node-schedule/node-schedule#299]
Hi there

I want a job to fire every month on the 1st day of the month at 00:02 am.

I've tried the following configurations and they all seem to fire daily at 00:02am:

1)  '0 2 0 1 \* ?'

2) 
    var rule = new schedule.RecurrenceRule();
    rule.dayOfMonth = 1;
    rule.hour = 0;
    rule.minute = 2;

3) {hour: 0, minute: 2, dayOfMonth: 1}

I'm not sure if this is an issue with my chron expression / configuration?

Please help!

**Comment by santigimeno** [comment]
@hashbangdev1 `2 0 1 * *` should work

**Comment by sunkuo** [comment]
@hashbangdev1 
 It is not a good idea to use 0 2 0 1 * ? . Because the symbol '?' in cron is confused and have different meaning in different implementations.
See   https://en.wikipedia.org/wiki/Cron
> In some implementations, used instead of '*' for leaving either day-of-month or day-of-week blank. Other cron implementations substitute "?" with the start-up time of the cron daemon

But in node-schedule , it use cron-parser(https://github.com/harrisiirak/cron-parser)  which not implement the ‘？’
<img width="408" alt="screen shot 2016-10-04 at 12 41 45 am" src="https://cloud.githubusercontent.com/assets/5069192/19045439/6208d834-89cb-11e6-8fdd-3286e6ab272b.png">

The true answer is _2 0 1 * *_ or _0 2 0 1 * *_   as @santigimeno  said

Don't believe it ? It is easy to validator it .  Remember node-schedule use cron-parser to parse cron string. Let use see the demo
<img width="396" alt="screen shot 2016-10-04 at 12 45 04 am" src="https://cloud.githubusercontent.com/assets/5069192/19045517/d1f9e80e-89cb-11e6-90da-c3e18ff8c84f.png">
Here is the result
<img width="427" alt="screen shot 2016-10-04 at 12 45 22 am" src="https://cloud.githubusercontent.com/assets/5069192/19045523/df046114-89cb-11e6-80c5-beea74dbb958.png">

Hope I can help

**Comment by hashbangdev1** [comment]
Thanks @sunkuo this looks better.

**Comment by santigimeno** [comment]
Closing this. Reopen if you think something else needs to be discussed
