### ISSUE TITLE
How to run a job every 7 seconds

### ISSUE THREAD

**Issue by rlaace423** [node-schedule/node-schedule#555]
Hello, I have a job to be executed every 7 seconds.
For that, I used node-schedule like below.
`schedule.scheduleJob('*/7 * * * * *', () => console.log(new Date().toString()));`

But It runs like,
Tue Dec 29 2020 12:35:28 GMT+0900 (GMT+09:00)
Tue Dec 29 2020 12:35:35 GMT+0900 (GMT+09:00)
Tue Dec 29 2020 12:35:42 GMT+0900 (GMT+09:00)
Tue Dec 29 2020 12:35:49 GMT+0900 (GMT+09:00)
Tue Dec 29 2020 12:35:56 GMT+0900 (GMT+09:00)
**Tue Dec 29 2020 12:36:00 GMT+0900 (GMT+09:00) --> ??**
Tue Dec 29 2020 12:36:07 GMT+0900 (GMT+09:00)
Tue Dec 29 2020 12:36:14 GMT+0900 (GMT+09:00)
Tue Dec 29 2020 12:36:21 GMT+0900 (GMT+09:00)

Job runs every 7 seconds well, but runs also every 0 which is not 7-times value.

How can I run a job every 7 seconds with node-schedule? If not, is there another way to overcome with?

**Comment by ChiweenieDijon** [comment]
Lucky issue #555!
If you haven't found it already, probably you need setInterval built in to node js:
https://nodejs.org/dist/latest-v12.x/docs/api/timers.html#timers_setinterval_callback_delay_args

**Comment by BehindTheMath** [comment]
This is caused by how cron-parser parses this type of expression, and I think it's by design, even though it can be confusing.

`*/` is not interpreted as "every 7 seconds starting from now". Rather, it's interpreted as: start from the first value (`0`), and add `7` until you reach the last value (`59`) (see the [crontab man pages](https://man7.org/linux/man-pages/man5/crontab.5.html)).

I don't think there's any way to do what you're trying to accomplish with this library. As suggested, `setInterval()` might be a better idea.

**Comment by kibertoad** [comment]
@rlaace423 See official documentation: `Node Schedule is for time-based scheduling, not interval-based scheduling.`.
For interval-based scheduling ("fire each 7 seconds"), `toad-scheduler` (https://github.com/kibertoad/toad-scheduler) is a much better fit.

**Comment by royt-via** [comment]
@rlaace423 @kibertoad 
you can just do `*/7 * * * * *`

**Comment by BehindTheMath** [comment]
As I mentioned [above](https://github.com/node-schedule/node-schedule/issues/555#issuecomment-766301678), `*/7` does not mean just every 7 seconds.
